/*
 * This source file was generated by the Gradle 'init' task
 */
package org.amadeus.amadeusserver;
import java.io.IOException;
import java.net.InetSocketAddress;

import org.json.JSONObject;

import com.sun.net.httpserver.HttpServer;

public class App {
    private static String processQuery(String query, String valueName) {
        String value = null;

        if (query != null) {
            query = "&" + query; 

            if (query.contains("&" + valueName + "=")) {
                value = query.substring(query.indexOf("&" + valueName + "=") + valueName.length() + 2); // 3. Changed +1 to +2 to account for the extra '&' character length
                value = value.split("&")[0];
            }
        }
        return value;
    }


    public static void setUpServer() throws IOException {
        HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);

        server.createContext("/api/hello", exchange -> {
            // this method runs when the client asks /api/hello
            String query = exchange.getRequestURI().getQuery();
            if (query != null) {
                if (query.contains("name=") && query.length() > 5) {
                    String name = processQuery(query, "name");
                    JSONObject jsonResponse = new JSONObject();
                    jsonResponse.put("message", "Hello " + name + "!");
                    String response = jsonResponse.toString();
                    exchange.getResponseHeaders().set("Content-Type", "application/json");
                    exchange.sendResponseHeaders(200, response.getBytes().length);
                    exchange.getResponseBody().write(response.getBytes());
                    exchange.close();
                } else {
                    JSONObject jsonResponse = new JSONObject();
                    jsonResponse.put("message", "No name provided");
                    String response = jsonResponse.toString();
                    exchange.getResponseHeaders().set("Content-Type", "application/json");
                    exchange.sendResponseHeaders(400, response.getBytes().length);
                    exchange.getResponseBody().write(response.getBytes());
                    exchange.close();
                }
            } else {
                    JSONObject jsonResponse = new JSONObject();
                    jsonResponse.put("message", "No name provided");
                    String response = jsonResponse.toString();
                    exchange.getResponseHeaders().set("Content-Type", "application/json");
                    exchange.sendResponseHeaders(400, response.getBytes().length);
                    exchange.getResponseBody().write(response.getBytes());
                    exchange.close();
            }
        });

        server.start();
    }

    public static void main(String[] args) {
        try {
            setUpServer();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}