/*
 * This source file was generated by the Gradle 'init' task
 */
package org.amadeus.amadeusserver;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        try {
            API.setUpServer();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
